// THIS FILE WAS GENERATED BY `build/ucd.zig`.
// DO NOT EDIT DIRECTLY.
pub const Bracket = struct {
    pair: u32,
    type: BracketType,
};
pub const BracketType = enum {
    opening,
    closing,
};
pub fn get(c: u32) ?Bracket {
    return switch (c) {
        '\u{0028}' => Bracket{
            .pair = '\u{0029}',
            .type = .opening,
        },
        '\u{0029}' => Bracket{
            .pair = '\u{0028}',
            .type = .closing,
        },
        '\u{005B}' => Bracket{
            .pair = '\u{005D}',
            .type = .opening,
        },
        '\u{005D}' => Bracket{
            .pair = '\u{005B}',
            .type = .closing,
        },
        '\u{007B}' => Bracket{
            .pair = '\u{007D}',
            .type = .opening,
        },
        '\u{007D}' => Bracket{
            .pair = '\u{007B}',
            .type = .closing,
        },
        '\u{0F3A}' => Bracket{
            .pair = '\u{0F3B}',
            .type = .opening,
        },
        '\u{0F3B}' => Bracket{
            .pair = '\u{0F3A}',
            .type = .closing,
        },
        '\u{0F3C}' => Bracket{
            .pair = '\u{0F3D}',
            .type = .opening,
        },
        '\u{0F3D}' => Bracket{
            .pair = '\u{0F3C}',
            .type = .closing,
        },
        '\u{169B}' => Bracket{
            .pair = '\u{169C}',
            .type = .opening,
        },
        '\u{169C}' => Bracket{
            .pair = '\u{169B}',
            .type = .closing,
        },
        '\u{2045}' => Bracket{
            .pair = '\u{2046}',
            .type = .opening,
        },
        '\u{2046}' => Bracket{
            .pair = '\u{2045}',
            .type = .closing,
        },
        '\u{207D}' => Bracket{
            .pair = '\u{207E}',
            .type = .opening,
        },
        '\u{207E}' => Bracket{
            .pair = '\u{207D}',
            .type = .closing,
        },
        '\u{208D}' => Bracket{
            .pair = '\u{208E}',
            .type = .opening,
        },
        '\u{208E}' => Bracket{
            .pair = '\u{208D}',
            .type = .closing,
        },
        '\u{2308}' => Bracket{
            .pair = '\u{2309}',
            .type = .opening,
        },
        '\u{2309}' => Bracket{
            .pair = '\u{2308}',
            .type = .closing,
        },
        '\u{230A}' => Bracket{
            .pair = '\u{230B}',
            .type = .opening,
        },
        '\u{230B}' => Bracket{
            .pair = '\u{230A}',
            .type = .closing,
        },
        '\u{2329}' => Bracket{
            .pair = '\u{232A}',
            .type = .opening,
        },
        '\u{232A}' => Bracket{
            .pair = '\u{2329}',
            .type = .closing,
        },
        '\u{2768}' => Bracket{
            .pair = '\u{2769}',
            .type = .opening,
        },
        '\u{2769}' => Bracket{
            .pair = '\u{2768}',
            .type = .closing,
        },
        '\u{276A}' => Bracket{
            .pair = '\u{276B}',
            .type = .opening,
        },
        '\u{276B}' => Bracket{
            .pair = '\u{276A}',
            .type = .closing,
        },
        '\u{276C}' => Bracket{
            .pair = '\u{276D}',
            .type = .opening,
        },
        '\u{276D}' => Bracket{
            .pair = '\u{276C}',
            .type = .closing,
        },
        '\u{276E}' => Bracket{
            .pair = '\u{276F}',
            .type = .opening,
        },
        '\u{276F}' => Bracket{
            .pair = '\u{276E}',
            .type = .closing,
        },
        '\u{2770}' => Bracket{
            .pair = '\u{2771}',
            .type = .opening,
        },
        '\u{2771}' => Bracket{
            .pair = '\u{2770}',
            .type = .closing,
        },
        '\u{2772}' => Bracket{
            .pair = '\u{2773}',
            .type = .opening,
        },
        '\u{2773}' => Bracket{
            .pair = '\u{2772}',
            .type = .closing,
        },
        '\u{2774}' => Bracket{
            .pair = '\u{2775}',
            .type = .opening,
        },
        '\u{2775}' => Bracket{
            .pair = '\u{2774}',
            .type = .closing,
        },
        '\u{27C5}' => Bracket{
            .pair = '\u{27C6}',
            .type = .opening,
        },
        '\u{27C6}' => Bracket{
            .pair = '\u{27C5}',
            .type = .closing,
        },
        '\u{27E6}' => Bracket{
            .pair = '\u{27E7}',
            .type = .opening,
        },
        '\u{27E7}' => Bracket{
            .pair = '\u{27E6}',
            .type = .closing,
        },
        '\u{27E8}' => Bracket{
            .pair = '\u{27E9}',
            .type = .opening,
        },
        '\u{27E9}' => Bracket{
            .pair = '\u{27E8}',
            .type = .closing,
        },
        '\u{27EA}' => Bracket{
            .pair = '\u{27EB}',
            .type = .opening,
        },
        '\u{27EB}' => Bracket{
            .pair = '\u{27EA}',
            .type = .closing,
        },
        '\u{27EC}' => Bracket{
            .pair = '\u{27ED}',
            .type = .opening,
        },
        '\u{27ED}' => Bracket{
            .pair = '\u{27EC}',
            .type = .closing,
        },
        '\u{27EE}' => Bracket{
            .pair = '\u{27EF}',
            .type = .opening,
        },
        '\u{27EF}' => Bracket{
            .pair = '\u{27EE}',
            .type = .closing,
        },
        '\u{2983}' => Bracket{
            .pair = '\u{2984}',
            .type = .opening,
        },
        '\u{2984}' => Bracket{
            .pair = '\u{2983}',
            .type = .closing,
        },
        '\u{2985}' => Bracket{
            .pair = '\u{2986}',
            .type = .opening,
        },
        '\u{2986}' => Bracket{
            .pair = '\u{2985}',
            .type = .closing,
        },
        '\u{2987}' => Bracket{
            .pair = '\u{2988}',
            .type = .opening,
        },
        '\u{2988}' => Bracket{
            .pair = '\u{2987}',
            .type = .closing,
        },
        '\u{2989}' => Bracket{
            .pair = '\u{298A}',
            .type = .opening,
        },
        '\u{298A}' => Bracket{
            .pair = '\u{2989}',
            .type = .closing,
        },
        '\u{298B}' => Bracket{
            .pair = '\u{298C}',
            .type = .opening,
        },
        '\u{298C}' => Bracket{
            .pair = '\u{298B}',
            .type = .closing,
        },
        '\u{298D}' => Bracket{
            .pair = '\u{2990}',
            .type = .opening,
        },
        '\u{298E}' => Bracket{
            .pair = '\u{298F}',
            .type = .closing,
        },
        '\u{298F}' => Bracket{
            .pair = '\u{298E}',
            .type = .opening,
        },
        '\u{2990}' => Bracket{
            .pair = '\u{298D}',
            .type = .closing,
        },
        '\u{2991}' => Bracket{
            .pair = '\u{2992}',
            .type = .opening,
        },
        '\u{2992}' => Bracket{
            .pair = '\u{2991}',
            .type = .closing,
        },
        '\u{2993}' => Bracket{
            .pair = '\u{2994}',
            .type = .opening,
        },
        '\u{2994}' => Bracket{
            .pair = '\u{2993}',
            .type = .closing,
        },
        '\u{2995}' => Bracket{
            .pair = '\u{2996}',
            .type = .opening,
        },
        '\u{2996}' => Bracket{
            .pair = '\u{2995}',
            .type = .closing,
        },
        '\u{2997}' => Bracket{
            .pair = '\u{2998}',
            .type = .opening,
        },
        '\u{2998}' => Bracket{
            .pair = '\u{2997}',
            .type = .closing,
        },
        '\u{29D8}' => Bracket{
            .pair = '\u{29D9}',
            .type = .opening,
        },
        '\u{29D9}' => Bracket{
            .pair = '\u{29D8}',
            .type = .closing,
        },
        '\u{29DA}' => Bracket{
            .pair = '\u{29DB}',
            .type = .opening,
        },
        '\u{29DB}' => Bracket{
            .pair = '\u{29DA}',
            .type = .closing,
        },
        '\u{29FC}' => Bracket{
            .pair = '\u{29FD}',
            .type = .opening,
        },
        '\u{29FD}' => Bracket{
            .pair = '\u{29FC}',
            .type = .closing,
        },
        '\u{2E22}' => Bracket{
            .pair = '\u{2E23}',
            .type = .opening,
        },
        '\u{2E23}' => Bracket{
            .pair = '\u{2E22}',
            .type = .closing,
        },
        '\u{2E24}' => Bracket{
            .pair = '\u{2E25}',
            .type = .opening,
        },
        '\u{2E25}' => Bracket{
            .pair = '\u{2E24}',
            .type = .closing,
        },
        '\u{2E26}' => Bracket{
            .pair = '\u{2E27}',
            .type = .opening,
        },
        '\u{2E27}' => Bracket{
            .pair = '\u{2E26}',
            .type = .closing,
        },
        '\u{2E28}' => Bracket{
            .pair = '\u{2E29}',
            .type = .opening,
        },
        '\u{2E29}' => Bracket{
            .pair = '\u{2E28}',
            .type = .closing,
        },
        '\u{2E55}' => Bracket{
            .pair = '\u{2E56}',
            .type = .opening,
        },
        '\u{2E56}' => Bracket{
            .pair = '\u{2E55}',
            .type = .closing,
        },
        '\u{2E57}' => Bracket{
            .pair = '\u{2E58}',
            .type = .opening,
        },
        '\u{2E58}' => Bracket{
            .pair = '\u{2E57}',
            .type = .closing,
        },
        '\u{2E59}' => Bracket{
            .pair = '\u{2E5A}',
            .type = .opening,
        },
        '\u{2E5A}' => Bracket{
            .pair = '\u{2E59}',
            .type = .closing,
        },
        '\u{2E5B}' => Bracket{
            .pair = '\u{2E5C}',
            .type = .opening,
        },
        '\u{2E5C}' => Bracket{
            .pair = '\u{2E5B}',
            .type = .closing,
        },
        '\u{3008}' => Bracket{
            .pair = '\u{3009}',
            .type = .opening,
        },
        '\u{3009}' => Bracket{
            .pair = '\u{3008}',
            .type = .closing,
        },
        '\u{300A}' => Bracket{
            .pair = '\u{300B}',
            .type = .opening,
        },
        '\u{300B}' => Bracket{
            .pair = '\u{300A}',
            .type = .closing,
        },
        '\u{300C}' => Bracket{
            .pair = '\u{300D}',
            .type = .opening,
        },
        '\u{300D}' => Bracket{
            .pair = '\u{300C}',
            .type = .closing,
        },
        '\u{300E}' => Bracket{
            .pair = '\u{300F}',
            .type = .opening,
        },
        '\u{300F}' => Bracket{
            .pair = '\u{300E}',
            .type = .closing,
        },
        '\u{3010}' => Bracket{
            .pair = '\u{3011}',
            .type = .opening,
        },
        '\u{3011}' => Bracket{
            .pair = '\u{3010}',
            .type = .closing,
        },
        '\u{3014}' => Bracket{
            .pair = '\u{3015}',
            .type = .opening,
        },
        '\u{3015}' => Bracket{
            .pair = '\u{3014}',
            .type = .closing,
        },
        '\u{3016}' => Bracket{
            .pair = '\u{3017}',
            .type = .opening,
        },
        '\u{3017}' => Bracket{
            .pair = '\u{3016}',
            .type = .closing,
        },
        '\u{3018}' => Bracket{
            .pair = '\u{3019}',
            .type = .opening,
        },
        '\u{3019}' => Bracket{
            .pair = '\u{3018}',
            .type = .closing,
        },
        '\u{301A}' => Bracket{
            .pair = '\u{301B}',
            .type = .opening,
        },
        '\u{301B}' => Bracket{
            .pair = '\u{301A}',
            .type = .closing,
        },
        '\u{FE59}' => Bracket{
            .pair = '\u{FE5A}',
            .type = .opening,
        },
        '\u{FE5A}' => Bracket{
            .pair = '\u{FE59}',
            .type = .closing,
        },
        '\u{FE5B}' => Bracket{
            .pair = '\u{FE5C}',
            .type = .opening,
        },
        '\u{FE5C}' => Bracket{
            .pair = '\u{FE5B}',
            .type = .closing,
        },
        '\u{FE5D}' => Bracket{
            .pair = '\u{FE5E}',
            .type = .opening,
        },
        '\u{FE5E}' => Bracket{
            .pair = '\u{FE5D}',
            .type = .closing,
        },
        '\u{FF08}' => Bracket{
            .pair = '\u{FF09}',
            .type = .opening,
        },
        '\u{FF09}' => Bracket{
            .pair = '\u{FF08}',
            .type = .closing,
        },
        '\u{FF3B}' => Bracket{
            .pair = '\u{FF3D}',
            .type = .opening,
        },
        '\u{FF3D}' => Bracket{
            .pair = '\u{FF3B}',
            .type = .closing,
        },
        '\u{FF5B}' => Bracket{
            .pair = '\u{FF5D}',
            .type = .opening,
        },
        '\u{FF5D}' => Bracket{
            .pair = '\u{FF5B}',
            .type = .closing,
        },
        '\u{FF5F}' => Bracket{
            .pair = '\u{FF60}',
            .type = .opening,
        },
        '\u{FF60}' => Bracket{
            .pair = '\u{FF5F}',
            .type = .closing,
        },
        '\u{FF62}' => Bracket{
            .pair = '\u{FF63}',
            .type = .opening,
        },
        '\u{FF63}' => Bracket{
            .pair = '\u{FF62}',
            .type = .closing,
        },
        else => null,
    };
}